### PR TITLE
expose privkey_tweak_add and pubkey_tweak_mul functions from lib

### PR DESCRIPTION
**Pull request by AdamISZ**
See #1

### CODE REVIEW

**Comment by ludbb** [comment]
It seems some assumptions were invalidated in the latest libsecp256k1, which resulted in this build failure.

Aside from that, would be against naming these functions as tweak_mul, tweak_add and add both of them to PrivateKey and PublicKey? That would be more inline with other functions.

**Comment by AdamISZ** [comment]
Renaming: of course, no problem.
Adding others: for adding pubkeys there is already combine(), right? For privkey_tweak_mul; sure, haven't really thought about it - didn't have a need for it myself.

**Comment by ludbb** [comment]
Yes, PublicKey.combine is there already.

**Comment by ludbb** [comment]
Let me know if you're planning to send an updated PR with these changes, thanks.

**Comment by AdamISZ** [comment]
Hi, sure, but I was just going to ask you: should I wait until the build is fixed? Otherwise I'll just resubmit with the names changed, is that OK?

**Comment by ludbb** [comment]
Since that comment the build has been fixed and the newer sig compact serialization functions and sig normalized have been exposed. IOW: the build is fine, please proceed :)

**Comment by g-p-g** [comment]
??

**Comment by g-p-g** [comment]
I'm also interested on this, is it being closed for a new PR or should I do it?

**Comment by AdamISZ** [comment]
Gimme a second :)

**Pull request closed without merging**
