### PR TITLE
expose privkey_tweak_add and pubkey_tweak_mul functions

### PR DESCRIPTION
**Pull request by AdamISZ**
See #1

### CODE REVIEW

**Comment by AdamISZ** [comment]
Yes, that last point is a good one. I may be misusing the underlying function; I'm not "tweaking" it.

**Comment by ludbb** [comment]
I believe you're, but it's returning a new one instead of modifying it in place. I think I like that more actually, thanks for submitting.

**Comment by ludbb** [comment]
Is it necessary to call secp256k1_ec_seckey_verify after secp256k1_ec_privkey_tweak_add assuming it succeeds?

**Comment by AdamISZ** [comment]
I think not, hence the comment. See secp256k1_scalar_add, there are checks there. I just wasn't 100% sure.

**Comment by ludbb** [comment]
Oh, so the comment was about that. Ok, I'm dropping it and will publish on pypi the updated version.

**Pull request merged**
