### PR TITLE
Port to Windows

### PR DESCRIPTION
**Pull request by chfast**
I'm working on porting this package to Windows. So far it is going ok, I was able to build a wheel package on Windows and upload it to PyPi (all tests passing).

I will try make linux easy installable too.

https://pypi.python.org/pypi/secp256k1-transient/0.11.1
https://travis-ci.org/chfast/secp256k1-py

### CODE REVIEW

**Comment by chfast** [comment]
Will you be interested in having Windows support for the current master branch?

**Comment by ludbb** [comment]
I won't be able to test it, but will take it if it works for you and others.

**Comment by ludbb** [comment]
Hello, sorry for the long delay on this. Would you be able to resolve the merge conflicts, and also consider https://github.com/ludbb/secp256k1-py/issues/13 where an user couldn't get your fork to compile?

**Comment by ludbb** [comment]
It seem this is out of date now, can you please indicate if you are interested in updating it to work with HEAD or not?

**Comment by chfast** [comment]
I think Ethereum switched to another Python bindings for secp256k1, so I don't care any more. Will you be able to provide Windows wheels for this one?

**Comment by ludbb** [comment]
Nope, closing this in that case.

**Pull request closed without merging**
