### PR TITLE
Automatically build bundled libsecp256k1 during install

### PR DESCRIPTION
**Pull request by ulope**
This PR adds the ability to install this wrapper without the need
to have a prior installation of libsecp256k1 on one's system.

This works as follows:

- During 'sdist':
  If the directory 'libsecp256k1' doesn't exist in the
  source directory it is downloaded from the location specified 
  by the `LIB_TARBALL_URL` constant in setup.py and extracted into
  a directory called 'libsecp256k1'

  To upgrade to a newer version of the bundled libsecp256k1 source
  simply delete the 'libsecp256k1' directory and update the 
  `LIB_TARBALL_URL` to point to a newer commit.

- During 'install':
  If an existing (system) installation of libsecp256k1 is found 
  (either in the default library locations or in the location pointed 
  to by the environment variable `LIB_DIR`) it is used as before.

  Due to the way the way cffi modules are implemented it is necessary
  to perform this detection in the cffi build module 
  '_cffi_build/build.py' as well as in 'setup.py'. For that reason
  some utility functions have been moved into a 'setup_support.py' 
  module which is imported from both.

  If however no existing installation can be found the bundled
  source code is used to build a library locally that will be 
  statically linked into the CFFI extension.

  By default only the 'recovery' module will be enabled in this bundled 
  version as it is the only one not considered to be 'experimental' by 
  the libsecp256k1 authors. It is possible to override this and enable 
  all modules by setting the environment variable 
  `SECP_BUNDLED_EXPERIMENTAL`.

Additionally there are some small other optimizations:

- The source code has been moved into a package so that site-packages 
  top-level doesn't get cluttered with the cffi generated source files.

- The cffi build script has been moved to a '_cffi_build' directory
  since it is not needed at runtime.

- The C-definitions used by cffi have been extracted into their own 
  files inside the '_cffi_build' directory to make the build script more
  readable.

### CODE REVIEW

**Comment by heikoheiko** [comment]
+1

**Comment by czepluch** [comment]
+1

**Comment by chfast** [comment]
Does it work on Windows?

**Comment by heikoheiko** [comment]
+1

**Comment by heikoheiko** [comment]
@ludbb any chance we get this merged? a lot of work went into this.

**Comment by ludbb** [comment]
Looking at this now, thanks for all the effort.

**Comment by ludbb** [comment]
Looks great, you should put your name on the setup.py as this is a very great contribution.

**Comment by ulope** [comment]
Thanks for merging :)

I have two small changes I'd like to add (lowering the minimum required setuptools version and a check for pkg-config). I'll open a separate PR for those.

**Pull request merged**
